name = "CAMMS"
uuid = "bb0db068-5fd7-4fec-b7aa-467cc8d3ff01"
authors = ["Francesc Turon <fturon@cimne.upc.edu>"]
version = "1.0.0-DEV"

[deps]
Gridap = "56d4f2e9-7ea1-5844-9cf6-b9c51ca7ce8e"
GridapGmsh = "3025c34a-b394-11e9-2a55-3fee550c04c8"

[compat]
julia = "1.8.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
